# Generated by Django 3.1.5 on 2021-01-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='content_types',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='disciplines',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
