# Generated by Django 3.1.5 on 2021-01-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20210120_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.weight'),
            preserve_default=False,
        ),
    ]
